import os

import pandas as pd
import plotly.express as px
import streamlit as st
from dotenv import load_dotenv
from google.cloud import bigquery


load_dotenv()

PROJECT_ID = os.getenv("GCP_PROJECT_ID")
MARTS_DATASET = os.getenv("BQ_MARTS_DATASET", "marts_recruitment")


st.set_page_config(
    page_title="Recruitment Analytics Dashboard",
    layout="wide",
)


@st.cache_resource
def get_bigquery_client():
    return bigquery.Client(project=PROJECT_ID)


@st.cache_data(ttl=300)
def run_query(query):
    client = get_bigquery_client()
    return client.query(query).to_dataframe()


def table_ref(table_name):
    return f"`{PROJECT_ID}.{MARTS_DATASET}.{table_name}`"


def load_executive_overview():
    query = f"""
        select *
        from {table_ref("mart_hr_executive_overview")}
        limit 1
    """
    return run_query(query)


def load_recruitment_funnel():
    query = f"""
        select *
        from {table_ref("mart_recruitment_funnel")}
        order by stage_order
    """
    return run_query(query)


def load_recruiter_performance():
    query = f"""
        select *
        from {table_ref("mart_recruiter_performance")}
    """
    return run_query(query)


def load_sla_breaches():
    query = f"""
        select *
        from {table_ref("mart_sla_breaches")}
        order by duration_days desc
    """
    return run_query(query)


def format_percentage(value):
    if pd.isna(value):
        return "0.0%"

    return f"{value * 100:.1f}%"


def format_number(value):
    if pd.isna(value):
        return "0"

    return f"{int(value)}"


st.title("Recruitment Analytics Dashboard")
st.caption(
    "Production-like mockup consuming BigQuery marts generated by dbt from Mock Greenhouse API data."
)

if not PROJECT_ID:
    st.error("Missing GCP_PROJECT_ID environment variable.")
    st.stop()

overview = load_executive_overview()
funnel = load_recruitment_funnel()
recruiter_performance = load_recruiter_performance()
sla_breaches = load_sla_breaches()

if overview.empty:
    st.error("No executive overview data found in BigQuery marts.")
    st.stop()

overview_row = overview.iloc[0]

st.subheader("Executive Overview")

col1, col2, col3, col4 = st.columns(4)

col1.metric("Open Jobs", format_number(overview_row["open_jobs"]))
col2.metric("Applications", format_number(overview_row["total_applications"]))
col3.metric("Hired", format_number(overview_row["hired_applications"]))
col4.metric(
    "Recruiter SLA Compliance",
    format_percentage(overview_row["recruiter_sla_compliance_rate"]),
)

col5, col6, col7, col8 = st.columns(4)

col5.metric("Rejected Applications", format_number(overview_row["rejected_applications"]))
col6.metric("Active Applications", format_number(overview_row["active_applications"]))
col7.metric("Total Offers", format_number(overview_row["total_offers"]))
col8.metric("Accepted Offers", format_number(overview_row["accepted_offers"]))

st.divider()

st.subheader("Recruitment Funnel")

if not funnel.empty:
    funnel_fig = px.bar(
        funnel,
        x="stage_name",
        y="applications_reached",
        title="Applications Reached by Recruitment Stage",
        labels={
            "stage_name": "Recruitment Stage",
            "applications_reached": "Applications Reached",
        },
    )
    st.plotly_chart(funnel_fig, use_container_width=True)

    st.dataframe(funnel, use_container_width=True)
else:
    st.info("No funnel data available.")

st.divider()

st.subheader("Recruiter Performance")

if recruiter_performance.empty:
    st.info("No recruiter performance data available.")
else:
    offices = sorted(
        recruiter_performance["office_name"].dropna().unique().tolist()
    )
    departments = sorted(
        recruiter_performance["department_name"].dropna().unique().tolist()
    )
    recruiters = sorted(
        recruiter_performance["recruiter_name"].dropna().unique().tolist()
    )

    filter_col1, filter_col2, filter_col3 = st.columns(3)

    selected_offices = filter_col1.multiselect(
        "Office",
        offices,
        default=offices,
    )

    selected_departments = filter_col2.multiselect(
        "Department",
        departments,
        default=departments,
    )

    selected_recruiters = filter_col3.multiselect(
        "Recruiter",
        recruiters,
        default=recruiters,
    )

    filtered_performance = recruiter_performance[
        recruiter_performance["office_name"].isin(selected_offices)
        & recruiter_performance["department_name"].isin(selected_departments)
        & recruiter_performance["recruiter_name"].isin(selected_recruiters)
    ]

    filtered_breaches = sla_breaches[
        sla_breaches["office_name"].isin(selected_offices)
        & sla_breaches["department_name"].isin(selected_departments)
        & sla_breaches["recruiter_name"].isin(selected_recruiters)
    ]

    if not filtered_performance.empty:
        performance_fig = px.bar(
            filtered_performance,
            x="recruiter_name",
            y="sla_compliance_rate",
            color="stage_name",
            title="SLA Compliance by Recruiter and Recruiter-Owned Stage",
            labels={
                "recruiter_name": "Recruiter",
                "sla_compliance_rate": "SLA Compliance Rate",
                "stage_name": "Stage",
            },
        )

        performance_fig.update_yaxes(tickformat=".0%")
        st.plotly_chart(performance_fig, use_container_width=True)

        performance_table = filtered_performance.copy()
        performance_table["sla_compliance_rate"] = (
            performance_table["sla_compliance_rate"] * 100
        ).round(1)
        performance_table["avg_duration_days"] = performance_table[
            "avg_duration_days"
        ].round(2)

        st.dataframe(performance_table, use_container_width=True)
    else:
        st.warning("No recruiter performance data for selected filters.")

    st.divider()

    st.subheader("SLA Breaches")

    if not filtered_breaches.empty:
        breach_table = filtered_breaches.copy()
        breach_table["duration_days"] = breach_table["duration_days"].round(2)

        st.dataframe(
            breach_table[
                [
                    "application_id",
                    "candidate_full_name",
                    "job_name",
                    "recruiter_name",
                    "department_name",
                    "office_name",
                    "stage_name",
                    "duration_days",
                    "sla_target_days",
                    "application_status",
                    "current_stage",
                ]
            ],
            use_container_width=True,
        )
    else:
        st.success("No SLA breaches for selected filters.")

st.divider()

st.subheader("Technical Lineage")

st.markdown("""
This dashboard consumes **BigQuery mart tables** produced by dbt.

Pipeline:

```text
Mock Greenhouse API
    ↓
Workato API Sync Simulator
    ↓
BigQuery RAW
    ↓
dbt STAGING
    ↓
dbt CORE
    ↓
dbt MARTS
    ↓
Streamlit Dashboard
The provided Excel and JSON files are used only to seed the Mock Greenhouse API.
The dashboard does not read those files directly.
""")
